# Generated by Django 4.1.3 on 2024-02-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='item',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='protein',
        ),
    ]
