# Generated by Django 4.1.3 on 2024-02-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_remove_item_calories_remove_item_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
