# Generated by Django 4.1.3 on 2024-02-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_remove_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
        migrations.AddField(
            model_name='item',
            name='cafe_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='commissary_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
