# Generated by Django 4.1.3 on 2024-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_remove_item_stock_item_cafe_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
