# Generated by Django 4.1.3 on 2024-02-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_transaction_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    ]
