# Generated by Django 4.1.3 on 2024-02-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_transaction_admin_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpoiledMaterialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoil_amount', models.IntegerField()),
                ('report_creator', models.CharField(max_length=64)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.item')),
            ],
        ),
    ]
