# Generated by Django 4.1.3 on 2024-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0007_spoiledmaterialreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approval',
            field=models.CharField(default='Pending', max_length=12),
        ),
    ]
