# Generated by Django 5.0.1 on 2024-02-26 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0009_alter_item_cafe_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
