# Generated by Django 5.0.1 on 2024-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0012_remove_item_um_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cafe_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='commissary_stock',
            field=models.FloatField(),
        ),
    ]
