# Generated by Django 5.0.1 on 2024-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0014_alter_spoiledmaterialreport_spoil_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='par_stock',
            field=models.FloatField(default=0),
        ),
    ]
